apiVersion: v1
kind: Service
metadata:
  name: fapi-service
  annotations:
    networking.gke.io/load-balancer-type: "Internal"
spec:
  selector:
    app: fapi
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
